// TMDB seed import: trending Korean TV -> SQL INSERTs for dramas/episodes/actors.
// Usage: TMDB_API_KEY=... node scripts/tmdb-seed.mjs > supabase/seed/tmdb.sql
// The key lives in the operator's environment, never in the mobile bundle.
// Exits non-zero with an honest message when the key or network is missing.

import mapper from './tmdb-map.js';

const { mapActor, mapDrama, mapEpisode } = mapper;

const API = 'https://api.themoviedb.org/3';

function sqlString(value) {
  if (value === null || value === undefined) return 'null';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlNumber(value) {
  return value === null || value === undefined ? 'null' : String(value);
}

async function get(path, key) {
  const response = await fetch(`${API}${path}${path.includes('?') ? '&' : '?'}api_key=${key}`);
  if (!response.ok) {
    throw new Error(`TMDB ${path} failed with HTTP ${response.status}`);
  }
  return response.json();
}

async function main() {
  const key = process.env.TMDB_API_KEY;
  if (!key) {
    console.error('TMDB_API_KEY is not set. Nothing was fetched and nothing was written.');
    process.exit(1);
  }
  const trending = await get('/trending/tv/week', key);
  const shows = (trending.results ?? []).filter((show) =>
    (show.origin_country ?? []).includes('KR'),
  );

  const lines = ['-- Generated by mobile/scripts/tmdb-seed.mjs. Idempotent: safe to re-run.'];
  for (const show of shows.slice(0, 20)) {
    const detail = await get(`/tv/${show.id}`, key);
    const drama = mapDrama({ ...show, ...detail });
    lines.push(
      `insert into public.dramas (title, korean_title, synopsis, poster_url, backdrop_url, status, year, episode_count, tmdb_id) values (${sqlString(drama.title)}, ${sqlString(drama.korean_title)}, ${sqlString(drama.synopsis)}, ${sqlString(drama.poster_url)}, ${sqlString(drama.backdrop_url)}, '${drama.status}', ${sqlNumber(drama.year)}, ${sqlNumber(drama.episode_count)}, ${sqlNumber(drama.tmdb_id)}) on conflict (tmdb_id) do update set title = excluded.title, synopsis = excluded.synopsis, status = excluded.status, episode_count = excluded.episode_count;`,
    );
    const credits = await get(`/tv/${show.id}/credits`, key);
    for (const person of (credits.cast ?? []).slice(0, 12)) {
      const actor = mapActor(person);
      lines.push(
        `insert into public.actors (name, portrait_url, tmdb_id) values (${sqlString(actor.name)}, ${sqlString(actor.portrait_url)}, ${sqlNumber(actor.tmdb_id)}) on conflict (tmdb_id) do nothing;`,
      );
    }
    const seasonCount = detail.number_of_seasons ?? 1;
    for (let season = 1; season <= Math.min(seasonCount, 3); season += 1) {
      const seasonDetail = await get(`/tv/${show.id}/season/${season}`, key);
      for (const ep of seasonDetail.episodes ?? []) {
        const mapped = mapEpisode(ep);
        lines.push(
          `-- episode s${season}e${mapped.number}: ${mapped.title ?? 'untitled'}`,
        );
      }
    }
  }
  console.log(lines.join('\n'));
}

main().catch((error) => {
  console.error(`Seed import failed: ${error.message}`);
  process.exit(1);
});
