/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DramaSlugRouteImport } from './routes/drama.$slug'
import { Route as EpisodeIdRouteImport } from './routes/episode.$id'
import { Route as PostIdRouteImport } from './routes/post.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DramaSlugRoute = DramaSlugRouteImport.update({
  id: '/drama/$slug',
  path: '/drama/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeIdRoute = EpisodeIdRouteImport.update({
  id: '/episode/$id',
  path: '/episode/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/drama/$slug': typeof DramaSlugRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/post/$id': typeof PostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/drama/$slug': typeof DramaSlugRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/post/$id': typeof PostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/drama/$slug': typeof DramaSlugRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/post/$id': typeof PostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create'
    | '/explore'
    | '/notifications'
    | '/profile'
    | '/drama/$slug'
    | '/episode/$id'
    | '/post/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create'
    | '/explore'
    | '/notifications'
    | '/profile'
    | '/drama/$slug'
    | '/episode/$id'
    | '/post/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/create'
    | '/explore'
    | '/notifications'
    | '/profile'
    | '/drama/$slug'
    | '/episode/$id'
    | '/post/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  DramaSlugRoute: typeof DramaSlugRoute
  EpisodeIdRoute: typeof EpisodeIdRoute
  PostIdRoute: typeof PostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drama/$slug': {
      id: '/drama/$slug'
      path: '/drama/$slug'
      fullPath: '/drama/$slug'
      preLoaderRoute: typeof DramaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$id': {
      id: '/episode/$id'
      path: '/episode/$id'
      fullPath: '/episode/$id'
      preLoaderRoute: typeof EpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  DramaSlugRoute: DramaSlugRoute,
  EpisodeIdRoute: EpisodeIdRoute,
  PostIdRoute: PostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
